### PR TITLE
fixed and closes #5

### LINKED ISSUE #5: Show
Link	/show/3
Location	Top right author image
Expected result	Mark Russell's quote
Routing Strategy	Wildcard routing
Required	Routing rule, leading to first/gimme/#), i.e. the "gimme" method inside the "First" controller, with that method defined to take a parameter
How to Fix It	Remapped using wildcard (show / digit)
Hint	application/controllers/First::gimme($id)

### PR DESCRIPTION
**Pull request by Alex-Zielinski**
Signed-off-by: Alex-Zielinski <alex.zielinski.bc@gmail.com>

### CODE REVIEW

File: application/config/routes.php [hunk 1]
```diff
@@ -55,6 +55,7 @@
 
 
 //custom routes
+$route['show/3'] = 'first/gimme/3';
```
Comment (isaacmorneau) [inline application/config/routes.php]: needs to be a number match
